version: "3.9"
services:

  db:
    image: postgres:13.6
    volumes:
      # The volume used for the database persistence.
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
    healthcheck:
      test: pg_isready -U ${DATABASE_USERNAME:-postgres} -h 127.0.0.1
      interval: 5s
    ports:
      - 5432:5432

  cache:
    image: redis:6.2.3
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - 6379:6379
    
volumes:
  data:
    driver: local
  redis:
    driver: local
